zestsoftware/zest.releaser

CHANGES.rst, zest/releaser/git.py, zest/releaser/longtest.py, zest/releaser/postrelease.py, zest/releaser/prerelease.py, zest/releaser/release.py, zest/releaser/svn.py, zest/releaser/tests/gitsvn.txt, zest/releaser/tests/hg.txt, zest/releaser/tests/release.txt, zest/releaser/tests/svn.txt, zest/releaser/utils.py
Trying it out as a pull request to get travis to test it.
Locally I get a lot of test errors, but that might just be version differences.
=> Only returning stderr if there's actually a non-zero exit code

zest/releaser/pypi.py, zest/releaser/tests/pypi.txt
@mauritsvanrees : ok to remove this safety valve? You're the one who works most with multiple servers in the .pypirc
=> Issue #74: remove pypi "Safety valve"

CHANGES.rst, zest/releaser/release.py
=> Clarified log message to say that an sdist/wheel is created in a temp folder

CHANGES.rst, doc/source/uploading.rst, setup.cfg, zest/releaser/baserelease.py, zest/releaser/pypi.py, zest/releaser/tests/baserelease.txt, zest/releaser/tests/functional-bzr.txt, zest/releaser/tests/functional-git.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_new.txt, zest/releaser/tests/pypirc_old.txt
=> Replace ci-skip option with extra-message option.

README.rst
I updated the list of dependencies and added ``[recommended]`` to the install instructions.
=> README update: dependencies

setup.py
=> Fixes for Python 2 install using pip

CHANGES.rst, zest/releaser/longtest.py
=> HTML encoding hint added to long description output

.travis.yml, CHANGES.rst
Trying without sudo again. Let's see what Travis says. I expect it to fail, but maybe something has been fixed meanwhile after all.
=> Maurits travis no sudo

CHANGES.rst, doc/source/entrypoints.rst, zest/releaser/prerelease.py, zest/releaser/svn.py, zest/releaser/tests/fullrelease.txt, zest/releaser/tests/svn.txt
Various roughly related changes. The changelog does a good job of describing them.
=> Check history

CHANGES.rst, README.rst, doc/source/entrypoints.rst, doc/source/options.rst, setup.py, zest/releaser/baserelease.py, zest/releaser/bumpversion.py, zest/releaser/postrelease.py, zest/releaser/preparedocs.py, zest/releaser/prerelease.py, zest/releaser/tests/addchangelogentry.txt, zest/releaser/tests/bumpversion.txt, zest/releaser/tests/utils.txt, zest/releaser/utils.py
=> Added bump version command

zest/releaser/baserelease.py, zest/releaser/preparedocs.py, zest/releaser/utils.py, zest/releaser/vcs.py
Mostly: split those functions up a bit. Plus a few code quality improvements.
This fixes several landscape.io warnings, especially that these functions had too many branches or too many local variables.
=> Made utils._execute_command and vcs._update_version simpler.

doc/source/options.rst, zest/releaser/pypi.py
=> Allow doubled % signs in date-format

CHANGES.rst, zest/releaser/svn.py
This fixes issue #213, which was on my list of things to look at somewhere in this decade...
Plus two minor improvements in related code.
@Niedes, can you check if this helps you?
=> Fix error for subversion when not in repository root

.gitignore, CHANGES.rst, buildout.cfg, doc/source/options.rst, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/tests/pypi.txt
=> Allow `{version}` in `tag-format`

CHANGES.rst, README.rst, doc/source/assumptions.rst, doc/source/versions.rst, zest/releaser/tests/vcs.txt, zest/releaser/vcs.py
This is another implementation of #230. I'm not really satisfied because this is more or less copy/pasted code. (If we decide to go this way, I'll integrate the docs in this PR too).
Let me know what you prefer :)
=> setup.cfg can also be a place to store the version

doc/source/developing.rst
- Doc: Document the need to configure localization for testing.
- ~~Tests/CI: Test Python 3.6, too.~~
- ~~Tests: Fix test-case for running commands.~~
I had to remove the third commit as it did solve #244 on my machine, made the test fail at travis.
=> Document the need to configure localization for testing

CHANGES.rst, doc/source/options.rst, zest/releaser/bzr.py, zest/releaser/git.py, zest/releaser/hg.py, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/svn.py, zest/releaser/tests/bzr.txt, zest/releaser/tests/git.txt, zest/releaser/tests/gitsvn.txt, zest/releaser/tests/hg.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/release.txt, zest/releaser/tests/svn.txt, zest/releaser/tests/vcs.txt, zest/releaser/vcs.py
=> Add option ``tag-message``.

zest/releaser/tests/pypi.txt
Another small change :-) Align with the text a few lines below – see review comment <https://github.com/zestsoftware/zest.releaser/pull/249#discussion_r150472374>.
=> Test doc: Minor rewording.

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/utils.py
Fixes https://github.com/zestsoftware/zest.releaser/issues/264.
=> Reorder encoding detection

doc/source/developing.rst
The shell-code was invalid. Also take the chance and remove redundancy in shell-code
=> Fix documentation how to configure localization for testing.

CHANGES.rst, zest/releaser/release.py
fixes https://github.com/zestsoftware/zest.releaser/issues/318
=> also accept statuscode 201 when uploading via twine

CHANGES.rst, zest/releaser/git.py
=> Use "git ls-files" as suggested by @mgedmin

.travis.yml
See https://travis-ci.community/t/cannot-install-git-svn-apt-package/863/8
=> Installing git-svn from git-core PPA

CHANGES.rst, zest/releaser/release.py
=> Fixed uploading to multiple servers if we do not want the first server.

CHANGES.rst, doc/source/options.rst, doc/source/uploading.rst, zest/releaser/baserelease.py, zest/releaser/pypi.py, zest/releaser/tests/baserelease.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_new.txt, zest/releaser/tests/pypirc_old.txt
=> 🐛 Add option to add message before the commit messages for zest.releaser 7.x

README.rst, doc/source/options.rst
We default to true since earlier this year.
=> Clarify the create-wheel option.

CHANGES.rst, doc/source/entrypoints.rst
=> Document hook package dir

zest/releaser/utils.py
- `pkg_resources` --> `importlib`
- `pkg_resources.parse_version` --> `packaging.version.parse`
Closes #453
=> Replace `pkg_resources`

CHANGES.rst, README.rst, doc/source/options.rst, doc/source/uploading.rst, pyproject.toml, zest/releaser/pypi.py, zest/releaser/tests/pypi.txt
=> Requiring "wheel" package

.readthedocs.yml, doc/source/conf.py
Readthedocs is complaining a bit: https://app.readthedocs.org/projects/zestreleaser/builds/27791670/
Hopefully this fixes the build. I might have to just merge it to get it to build there.
=> RTD tweaks
