zest/releaser/utils.py
`utils.system` - Replacing the entire environment causes Windows Side-by-side to freak out since %SYSTEMROOT% is missing, so preserve (and update) the environment when calling subprocesses.
See #72 for more details.
=> Fix for #72 - WindowsError while getting version

zest/releaser/vcs.py
Fix for issue https://github.com/zestsoftware/zest.releaser/issues/70
As the docstring mentions, [`vcs.py:BaseVersionControl._update_version`](https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/vcs.py#L175-229) looks in 3 places for a version number. The first 2 chunks of code look for the version number, and if found, make their change and return. I've refactored the 3rd chunk to match this pattern. This has the advantage of no longer re-writing setup.py when there are no changes, and no longer logging a message reporting success, regardless of outcome.
Instead we return if version is found, otherwise raise an Exception. Let me know if there's a particular exception class I should use instead of `Exception`.
Feedback welcome.
=> Issue70 unwriteable version halt

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/postrelease.py, zest/releaser/prerelease.py, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/tests/functional-bzr.txt, zest/releaser/tests/functional-git.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_new.txt, zest/releaser/tests/pypirc_old.txt
This avoids running Travis Continuous Integration builds.  See
http://docs.travis-ci.com/user/how-to-skip-a-build/
To activate this, add '[zest.releaser] ci-skip = yes' to the
'setup.cfg' of a package, or your global '~/.pypirc'.
Eric Steele wants something like this for Plone. :-)
Alternatives I can think of:
- Always do this automatically when you have a `.travis.yml` in your repo.
- Do this in a separate package, using the hooks of zest.releaser.
=> Add '[ci skip]' to commit messages.

CHANGES.rst, buildout.cfg, doc/source/uploading.rst, setup.cfg, setup.py, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_yes_release.txt
Use the new zest.releaser[recommended] extra, or pip install
wheel yourself next to zest.releaser.
Issue #55
=> Add optional support for uploading Python wheels.

CHANGES.rst, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/tests/functional-svn.txt, zest/releaser/tests/functional.py, zest/releaser/tests/pypi.txt, zest/releaser/tests/test_setup.py, zest/releaser/tests/utils.txt, zest/releaser/utils.py
That package was a backport from distutils for Python 2.5 and earlier,
which we do not support.
@reinout, want to have a look to see if my assumptions are wrong and I break something?
=> Remove code for support of collective.sdist.

CHANGES.rst, zest/releaser/prerelease.py, zest/releaser/tests/fullrelease.txt, zest/releaser/tests/functional.py, zest/releaser/tests/postrelease.txt
When between the last postrelease and a new prerelease a changelog entry
has not been added, '- Nothing changed yet' would still be in there.
Issue #26.
=> Warn when no changelog entry has been added.

.gitignore, tox.ini
tox.ini is becoming the standard way to run tests on an unfamiliar
Python package.  Bonus points: it lets you rest with multiple Python
versions conveniently, which is *essential* should you wish to add
Python 3 support.
=> Add a tox.ini

CHANGES.rst, zest/releaser/tests/utils.txt, zest/releaser/utils.py
Actually: postrelease *and* prerelease. Any part where we call `ask_version`.
Example commit that we want to avoid here:
https://github.com/plone/plone.app.testing/commit/81c54c6adc72ace456b40cda327f0b8d3bbbf55a
(I have reverted that one in https://github.com/plone/plone.app.testing/commit/24663b9b90d6d849045c75303a0cfc4c4dcbf2d3)
=> Maurits postrelease version check

zest/releaser/vcs.py
The match should be anchored to the beginning of the line, because the 
replacement will replace the entire line.
The match should not allow non-whitespace characters around the '=', except
for the beginning of the string literal.
Fixes #99.
=> Stricter version regexps

zest/releaser/longtest.py
Some improvements & fixes for #103 
- Clearer error messages.
- Long description error is printed again (only printing "it is invalid" isn't helpful).
- The tempfile didn't have a `.html` extension (only `html` as a postfix, not an extension)
=> Readme fixes

zest/releaser/svn.py, zest/releaser/tests/functional-svn.txt, zest/releaser/tests/svn.txt
If there are certificate errors these are silently dropped into output making for strange behaviour without this option.
=> Always use --non-interactive for svn commands.

CHANGES.rst, zest/releaser/utils.py
Otherwise in case of a problem it was not clear why the command
stopped.
Done simply by changing logger.debug to logger.info...
Also switched the order around: first show the question, then the
answer we give.
Fixes issue #136.
=> When using the '--no-input' option, show question and answer.

CHANGES.rst, zest/releaser/prerelease.py, zest/releaser/tests/fullrelease.txt
Issue #155.
Implementation: we grab the version and the history twice:
- Initially in read-only mode: check current version and history and
maybe warn about problems.
- Then show the changelog of the current release as found in the
history.  Include the header and underline of the previous release
for reference.
- Then grab the version in write mode: ask for the new version number.
- Then grab the history in write mode: take over the new version number.
=> Show changelog of current release before asking for new version.

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/pypi.py, zest/releaser/tests/fullrelease.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_no_input.txt
This provides a fix for https://github.com/zestsoftware/zest.releaser/issues/164
=> Add "no-input" to global options

CHANGES.rst, zest/releaser/git.py
This will improve the release time a lot on big repositories.
See https://github.com/zestsoftware/zest.releaser/issues/169
=> Do a shallow clone

CHANGES.rst, zest/releaser/git.py, zest/releaser/tests/git.txt
See issue #169. Addresses the concern I raised in pull request #170.
The only tricky thing was fixing a test, which unexpected did a commit between creating the tag and doing the clone.
=> Really create a shallow git clone when creating a distribution.

doc/source/developing.rst, tox.ini
Python 3.5 has been used for testing by Travis since the 21st of April 2016. This PR updates the docs to reflect this and adds a py35 environment to ``tox.ini`` too.
=> Updated tox.ini and docs to reflect testing with Python 3.5

README.rst
zest.releaser recognizes a CHANGES file with extension md. The README only mentioned extensions rst, txt, and markdown, or no extension at all. I could not imagine .md was not recognized so I looked through the code and see there, it is supported. To avoid other developers having to do the same, I updated the README.
=> Mentions support for a CHANGES file with extension .md in README

CHANGES.rst, doc/source/uploading.rst
We are not using `setup.py register/upload` anymore, but use twine for both.
Removed the old-style `.pypirc` from the docs.
This builds on and replaces pull request #185
=> Updated the documentation on uploading.

zest/releaser/tests/test_setup.py
I got this failure locally:
```
File "/Users/maurits/tools/src/zest.releaser/zest/releaser/tests/functional-git.txt", line 163, in functional-git.txt
Failed example:
print(execute_command("git status"))
Differences (ndiff with -expected +actual):
On branch master
- nothing to commit, working directory clean
?                            ^^  ^^^^^
+ nothing to commit, working tree clean
?                            ^  ^
+ <BLANKLINE>
```
See explanation for the change in this git commit: https://github.com/git/git/commit/2a0e6cdedab306eccbd297c051035c13d0266343
This pull request fixes our tests.
=> Fixed tests with git 2.9.1+.

CHANGES.rst, doc/source/uploading.rst, setup.py, zest/releaser/tests/test_setup.py, zest/releaser/utils.py
Fixes https://github.com/zestsoftware/zest.releaser/issues/183
Note: this means that there actually is no version of zest.releaser that works with twine 1.7.x. But that's okay.
=> Support and require twine 1.8.0 as minimum version.

zest/releaser/release.py
Create the list of distributions after the before_upload hook has fired.
This allows the before_upload hook to create additional distributions,
which will then be uploaded.
=> Allow `before_upload` hook to create dists

CHANGES.rst, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_both.txt, zest/releaser/tests/pypirc_simple.txt
Previously, we required either a `server-login` section with a `username` option, or a `distutils` section with an `index-servers` option.  Failing this, we gave a warning about a not properly configured file, and happily continued without uploading anything. Now if there is something missing from the `pypirc` file, we give an error and explicitly ask if you want to continue without uploading.
Fixes issue #199.
Note for developers of extensions for `zest.releaser`: this removes the `is_old_pypi_config` and `is_new_pypi_config` methods, because they made no sense anymore.  If you were using these, see if you can use the `distutils_server` method instead.
=> Allow `pypirc` with just a `pypi` section.

CHANGES.rst, doc/source/options.rst, zest/releaser/bumpversion.py, zest/releaser/postrelease.py, zest/releaser/pypi.py, zest/releaser/tests/utils.txt, zest/releaser/utils.py
This influences the suggested version.  The defaults give the same results as previously. I tested this by copying the `utils.txt` tests from this branch, removing the lines that use the new options, and running them with the code from the master branch.
I myself am going to prefer `less-zeroes = yes` and `version-levels = 3` in my `~/.pypirc`, which gives the results that the Plone Release Team prefers.
The options are documented in `options.rst`, copied here for good measure:
**less-zeroes = yes / no**
Default: no.
This influences the version suggested by the bumpversion command.
When set to true:
- Instead of 1.3.0 we will suggest 1.3.
- Instead of 2.0.0 we will suggest 2.0.
**version-levels = a number**
Default: 0.
This influences the version suggested by the postrelease and …
=> Added version-levels and less-zeroes options.

CHANGES.rst, doc/source/options.rst, zest/releaser/bumpversion.py, zest/releaser/postrelease.py, zest/releaser/pypi.py, zest/releaser/tests/utils.txt, zest/releaser/utils.py
This builds on pull request #204 because it would otherwise cause merge conflicts.
This replaces pull request #176. I did some minor changes and addressed the [comment by @drucci](https://github.com/zestsoftware/zest.releaser/pull/176#issuecomment-219068856) about a change needed in `suggest_version`.
=> Override dev marker

doc/source/options.rst, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/tests/release.txt, zest/releaser/vcs.py
This PR adds a tag formatter in the `.pypirc` options  and should resolve #157
Do let me know if I missed something and am happy to change it.
=> Add tag formatter in the config

CHANGES.rst, zest/releaser/tests/vcs.txt, zest/releaser/vcs.py
=> Support uppercase `VERSION = ` in setup.py, fixes #216

zest/releaser/git.py
I use the linux subsystem in windows all the time. It maps things to my windows username, which in this case happens to be "/mnt/c/Users/Gavin Mogan" so when the git clone happens, it thinks its multiple parameters.
Quote the path so it doesn't care about spaces.
=> Escape git clone path so it works when windows drives are mounted

CHANGES.rst, doc/source/options.rst, zest/releaser/utils.py
Hi there!
We have a use case where we really don't want the hooks to be skipped when they cannot be imported.
So I added an option, with current behaviour as default :)
I'm kinda puzzled with the way I should test this, I would be grateful if you had some insights about the best way to do it!
Thanks, and also thanks for this awesome tool ;)
=> Add skip-missing-hooks option

CHANGES.rst, doc/source/options.rst, setup.cfg, zest/releaser/bzr.py, zest/releaser/git.py, zest/releaser/hg.py, zest/releaser/pypi.py, zest/releaser/release.py, zest/releaser/svn.py, zest/releaser/tests/release.txt, zest/releaser/vcs.py
This does not include test-cases, since these would require interaction for the actually gpg-signing.
Closes #152, albeit this only implements tag-signing. If somebody wants to sign every commit, this ought to be done in the VCS' configuration anyway.
=> Add option ``tag-signing``.

zest/releaser/bzr.py, zest/releaser/git.py, zest/releaser/hg.py, zest/releaser/lasttaglog.py, zest/releaser/release.py, zest/releaser/svn.py, zest/releaser/tests/bzr.txt, zest/releaser/tests/fullrelease.txt, zest/releaser/tests/functional-bzr.txt, zest/releaser/tests/functional-git.txt, zest/releaser/tests/functional-mercurial.txt, zest/releaser/tests/functional-svn.txt, zest/releaser/tests/functional-with-hooks.txt, zest/releaser/tests/functional.py, zest/releaser/tests/git.txt, zest/releaser/tests/gitsvn.txt, zest/releaser/tests/hg.txt, zest/releaser/tests/postrelease.txt, zest/releaser/tests/prerelease.txt, zest/releaser/tests/svn.txt, zest/releaser/tests/utils.txt, zest/releaser/utils.py, zest/releaser/vcs.py
This avoids wrong quoting in arguments if one e.g. passes a
double-quote in a message.
- Convert all command-strings into lists.
- New function ``utils.excute_commands()`` (plural).
- New function ``utils.format_commands()``.
- Incompatible: ``git.cmd_checkout_from_tag()`` now returns a list
of commands, not a single one.
- Adjusted tests.
Closes #233.
=> Use list of arguments for execute_command, not a string.

doc/source/credits.rst, doc/source/developing.rst, doc/source/index.rst, doc/source/project.rst
- Reorder documentation sections.
- Shorten "Developer" section title.
- Shorten "Project" title in the contents side-bar.
I've put thse into a pull-request of it's own since they might be a bit controversy.
=> Doc updates: Reorder sections and shorten titles

zest/releaser/git.py, zest/releaser/tests/git.txt
You can never have enough tests :-)
=> Bugfix for "git --sign" typo

CHANGES.rst, zest/releaser/tests/test_setup.py
I updated with mac homebrew to mercurial 4.4.1 today (I don't know what the previous version exactly was).
This gave a test error because it prints an extra line.
```
File "/Users/maurits/tools/src/zest.releaser/zest/releaser/tests/hg.txt", line 127, in hg.txt
Failed example:
checkout.checkout_from_tag('0.1')
Differences (ndiff with -expected +actual):
-
adding changesets
adding manifests
adding file changes
- added 2 changesets with ... changes to 17 files
?                         ^^^
+ added 2 changesets with 18 changes to 17 files
?                         ^^
+ new changesets 234567890abc:234567890abc
updating to branch default
17 files updated, 0 files merged, 0 files removed, 0 files unresolved
+ <BLANKLINE>
```
I fixed it by removing this line in our test output normalizer.
=> Fixed tests with mercurial 4.4+.

zest/releaser/utils.py
Set iteration order is not defined in Python.  This loop is one where the order *matters*, otherwise we could be "upgrading" to UTF-8 without any reason, leading to bugs like #254.
I have not tested that this fix works.
I don't currently have the time to write a unit test that would expose the bug.
=> Try output encodings in the right order please

bootstrap.py, buildout.cfg
There is a failure on Travis with Python 2.7 running buildout, failing to downgrade `six` from 1.11.0 to 1.10.0.
I guess this won't fix it, but there may be a chance, and updating the bootstrap.py is good.
We can try other stuff if this fails.
=> Use fresh https://bootstrap.pypa.io/bootstrap-buildout.py

zest/releaser/utils.py
This patch seems to fix #256, but I've only tested on my Windows machine.
=> Write text files with correct encoding on Python3

CHANGES.rst, zest/releaser/vcs.py
I got this in a project where the `setup.py` had the version in `__version__` so it could not be written back. `zest.releaser` then reads `setup.cfg` to see if it has a hint on where to find the version. But when `setup.cfg` is missing, it fails:
```
Traceback (most recent call last):
File "/Users/maurits/tools/bin/prerelease", line 45, in <module>
sys.exit(zest.releaser.prerelease.main())
File "/Users/maurits/tools/src/zest.releaser/zest/releaser/prerelease.py", line 104, in main
prereleaser.run()
File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease.py", line 353, in run
self.execute()
File "/Users/maurits/tools/src/zest.releaser/zest/releaser/prerelease.py", line 68, in execute
self._write_version()
File "/Users/maurits/tools/src/zest.releaser/zest/releaser/baserelease. …
```
=> Fixed IOError when ``setup.cfg`` is missing and no version is found.

CHANGES.rst, zest/releaser/bumpversion.py, zest/releaser/postrelease.py, zest/releaser/prerelease.py
Fixes issue #262.
There were several checks like this already. I made them the same: do not compare with `None`, but check for a False value. That would catch a found but empty version as well.
=> Quit in postrelease when we cannot find a version.

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/svn.py, zest/releaser/tests/utils.txt, zest/releaser/utils.py, zest/releaser/vcs.py
You could get ugly output like this:
INFO: The '[u'git', u'diff']':
Brackets would be printed in all Python versions.
On Python 2 you could get a `u'unicode'` marker.
It doesn't happen always; it depends on how everything is called.
Hard to say if this catches them all: in the tests we normalize the difference, so you can't see it.
=> Print commands in a nicer way.

CHANGES.rst, zest/releaser/pypi.py
If you had a password with a percentage sign, you could get an error.
Fixes https://github.com/zestsoftware/zest.releaser/issues/271.
There might be other places where we need to do this, but it is hard to say where interpolation may be useful and where it may be harmful.
=> Get PyPI password raw, without interpolation.

CHANGES.rst, doc/source/options.rst, zest/releaser/baserelease.py, zest/releaser/pypi.py, zest/releaser/tests/vcs.txt, zest/releaser/utils.py, zest/releaser/vcs.py
Fixes issue #264, see discussion there.
I fought a bit with the difference between a few possibilities to read this:
- create a `SetupConfig` object and read the encoding option directly in the calling code (`if setup_config.config.has_option(...)`
- create a `PypiConfig` object, which also reads `setup.cfg` and use a new method `encoding` on that class.
I opted for the second way.
That also meant that I found an undocumented option `history_file` and changed that to use the second way. So I included that in this PR. I kept the commits separate, so you can view them separately if you want.
=> Encoding config option

CHANGES.rst, zest/releaser/postrelease.py, zest/releaser/prerelease.py, zest/releaser/utils.py
This replaces PR #279.
This is in prerelease and postrelease data.
Plugins can use this to tell `zest.releaser` (and other plugins) to not touch the history, presumably because the plugin itself handles it.
Default value is True: do update history.
The `update_history` key will be used by a towncrier plugin that will update the changelog with news fragments.
The towncrier plugin will add an internal data key `_towncrier_applicable`.
With this, you would get this warning when running zest.releaser:
Internal detail: key(s) ['_towncrier_applicable'] are not documented
So I have changed this internal check to allow undocumented data keys when they start with underscore.
=> Added key update_history in data.

CHANGES.rst, README.rst, doc/source/entrypoints.rst, doc/source/uploading.rst, zest/releaser/release.py, zest/releaser/tests/functional.py
One real code change, the rest is documentation or tests.
Fixes issue #281.
=> Use pypi.org, especially when checking if a package is on PyPI.

CHANGES.rst, zest/releaser/tests/vcs.txt, zest/releaser/vcs.py
This fixes #301.
The first commit demonstrates the issue. After that one fails, the second commit fixes it.
=> Retain quote style for version strings in setup.py

CHANGES.rst, zest/releaser/bumpversion.py, zest/releaser/tests/bumpversion.txt
This prevents `1.10` from being less than `1.9`
There's no separate test as the test setup drives me mad. The existing functionality still works like a charm, though.
=> Comparing versions as versions, not strings (fixes #299)

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/bumpversion.py, zest/releaser/postrelease.py, zest/releaser/prerelease.py
Fixes issue #310.
See also https://github.com/collective/zestreleaser.towncrier/pull/11
=> Let bumpversion respect the update_history data.

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/tests/postrelease.txt
We look for "unreleased" in it.  Give a warning when this happens.
Fixes issue #311.
This is a more general fix than the one in PR #313 which is specific for `bumpversion`. But it seems good to do both.
The current one might possibly have negative side effects when people do not have 'unreleased' in their changelog, but say `(release date to be determined)`. So it could be that this fixes some things and breaks something else. To counter this, we might just need support for an extra item in `setup.cfg`, `unreleased-marker` similar to the `development-marker` that we already have.
But it already fixes something in the tests: in `postrelease.txt` we call `prerelease` and until now this would change `1.0 (1972-12-25)` into `1.3 (<today>)`. With the current PR, it keeps the header, and it …
=> Refuse to edit history header when it may be from already released version

CHANGES.rst, zest/releaser/pypi.py
No longer check if this should be a universal wheel or not.
That is handled automatically when calling `python setup.py bdist_wheel`.
You can still set `[zest.releaser] create-wheel = no` to prevent creating a wheel.
This fixes issue #315.
=> When bdist_wheel is in setup.cfg, release a wheel.

zest/releaser/addchangelogentry.py
Currently, an `addchangelogentry` command just adds a new entry to a changelog and leaves `Nothing changed yet.` message untouched. This PR adds a removal of "nothing changed" message when it is the first message in an unreleased section.
=> Remove nothing_changed_yet line from history lines in unreleased section.

CHANGES.rst, zest/releaser/choose.py, zest/releaser/tests/choose.txt
When you were not in the root of a repo, `zest.releaser` already asked if you wanted to go there.
The default answer has now changed from yes to no.
See issue #326.
=> Do not go to the root of the repo by default.

buildout.cfg
I hope this fixes Travis.
We get too new versions of packages, that are not compatible.
Works locally for Python 2.7 and PyPy.
(`git svn` tests are failing because I don't have this properly installed anymore it seems. And only on PyPy a few mercurial tests fail because of a missing user name, which is not the case on 2.7. But this is both likely only a local problem.)
=> Pin more versions on Python 2.7 (and PyPy).

zest/releaser/baserelease.py, zest/releaser/utils.py
I bumped into a couple of issues using the latest version of zest.releaser under python 2.7, while trying to release code that uses git and git-lfs.
This PR address both these issues.
=> Fix TypeError on Python 2.7 and git-lfs issue

README.rst, setup.py, zest/releaser/baserelease.py, zest/releaser/pypi.py, zest/releaser/tests/utils.txt, zest/releaser/utils.py
The main ones:
- Always use tokenize.open instead of chardet to detect the encoding.
We meant chardet for Python 2, although theoretically it might
be needed in corner cases on Python 3.  Let's try without it.
- Use shlex.quote instead of our simpler quoting in format_command.
=> Removed Python 2 fallbacks.

CHANGES.rst, zest/releaser/tests/cmd_error.py, zest/releaser/tests/utils.txt, zest/releaser/utils.py
If I recall correctly, our `_execute_command` function started out as a copy of some code from `zc.buildout`, with as comment that it was a "commands.getoutput() replacement that also works on windows".
Meanwhile, the entire [`commands` module was removed in Py 3](https://docs.python.org/2.7/library/commands.html?highlight=commands#module-commands)  and you should use `subprocess` now.
We already did this, but we were using `subprocess.Popen`. The [`subprocess` documentation says](https://docs.python.org/3.10/library/subprocess.html):
> The recommended approach to invoking subprocesses is to use the run() function for all use cases it can handle. For more advanced use cases, the underlying Popen interface can be used directly.
> The run() function was added in Python 3.5
It looks like our …
=> Use subprocess.run for executing commands

CHANGES.rst, zest/releaser/longtest.py
In order to avoid discovering description format issues when uploading to Pypi, I would like to use `longtest` in a CI job.
One idea was to pass a flag that would skip the browser step. What do you think?
=> Add --headless option for longtest

CHANGES.rst, setup.py, zest/releaser/prerelease.py
Fixes https://github.com/zestsoftware/zest.releaser/issues/381
I added `pep440` to the `recommended` extra, not to the core dependencies: `zest.releaser` can also be used for non-Python projects.
Sample `prerelease` run with bad versions:
```
Enter version [7.0.0a3]: bad-version-1
WARNING: 'bad-version-1' is not a canonical Python package version.
Do you want to use this version anyway? (Y/n)? n
Enter version [7.0.0a3]: even worse version 2
WARNING: 'even worse version 2' is not a canonical Python package version.
Do you want to use this version anyway? (Y/n)? y
INFO: Set setup.py's version to 'even worse version 2'
INFO: Changed version from 7.0.0a3.dev0 to even worse version 2
```
I tried adding tests, but could not get it to work.
=> In prerelease, check with pep440 if the version is canonical.

zest/releaser/tests/postrelease.txt
An extra question is asked because we try to set a non-canonical version. Sample failure:
```
File "/Users/maurits/community/zest.releaser/zest/releaser/tests/postrelease.txt", line 130, in postrelease.txt
Failed example:
prerelease.main()
Differences (ndiff with -expected +actual):
- Question...
+ Question: Run pyroma on the package before tagging? (Y/n)? 
+ Our reply: <ENTER>
+ Question: Do you want to run check-manifest? (Y/n)? 
+ Our reply: <ENTER>
+ lists of files in version control and sdist match
+ Changelog entries for version 0.2.20:
+ <BLANKLINE>
+ 0.2.20 (unreleased)
+ -------------------
+ <BLANKLINE>
+ - Brown bag release.
+ <BLANKLINE>
+ <BLANKLINE>
+ 0.2.19 (1972-12-25)
+ -------------------
- Question: Enter version [0.2.20]:
+ Question: Enter version [0.2.20]: 
? …
```
=> Fix postrelease tests.

.github/workflows/tests.yml, CHANGES.rst, setup.py, tox.ini, zest/releaser/tests/addchangelogentry.txt, zest/releaser/tests/baserelease.txt, zest/releaser/tests/bumpversion.txt, zest/releaser/tests/choose.txt, zest/releaser/tests/fullrelease.txt, zest/releaser/tests/functional-git.txt, zest/releaser/tests/functional-with-hooks.txt, zest/releaser/tests/git.txt, zest/releaser/tests/postrelease.txt, zest/releaser/tests/preparedocs.txt, zest/releaser/tests/prerelease.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/release.txt, zest/releaser/tests/test_setup.py, zest/releaser/tests/utils.txt, zest/releaser/tests/vcs.txt
`z3c.testsetup` is incompatible with Python 3.11.
Fixes https://github.com/zestsoftware/zest.releaser/issues/12 (or at least part of it).
=> Add support for Python 3.11, remove z3c.testsetup

CHANGES.rst, doc/source/options.rst, zest/releaser/bumpversion.py, zest/releaser/tests/bumpversion.txt, zest/releaser/tests/utils.txt, zest/releaser/utils.py
This removes alpha / beta / rc markers from the version.
Use case: Plone 6.0 has a first release candidate and the version pins contain a lot of alpha, beta, and rc releases. Before the final release, I want to make final releases of the dependencies. I know I won't remember to do this manually for all packages, so I automate it. :-)
Output from a sample run in the `Plone` package, redacted for brevity/clarity:
```
$ bumpversion --final
Checking version bump for final release.
Last tag: 6.0.0rc1
Current version: 6.0.0rc2.dev0
Enter version [6.0.0.dev0]:
INFO: Set setup.cfg's version to '6.0.0.dev0'
INFO: Changed version from 6.0.0rc2.dev0 to 6.0.0.dev0
INFO: History file CHANGES.rst updated.
INFO: The 'git diff':
diff --git a/CHANGES.rst b/CHANGES.rst
-6.0.0rc2 (unreleased) …
```
=> Add --final option to bumpversion command.

CHANGES.rst, doc/source/options.rst, zest/releaser/postrelease.py, zest/releaser/tests/postrelease.txt
This continues the work by @rnc from PR #393. That PR was waiting for a rebase or merge. And today I added the `--final` option to `bumpversion` so it made sense for me to include it for `postrelease` as well.
=> Add all bumpversion options to the postrelease command.

.github/workflows/tests.yml, CHANGES.rst, doc/source/options.rst, zest/releaser/baserelease.py, zest/releaser/pypi.py, zest/releaser/tests/baserelease.txt, zest/releaser/tests/bumpversion.txt, zest/releaser/tests/functional.py, zest/releaser/utils.py
=> Support Markdown for History/Changelog

CHANGES.rst, doc/source/options.rst, setup.py, zest/releaser/git.py, zest/releaser/pypi.py, zest/releaser/tests/functional.py, zest/releaser/tests/git.txt, zest/releaser/vcs.py
Default: no.
When set to true, pre commit hooks are run.
This may interfere with releasing when they fail.
cc @sneridagh who has hit by this today.
=> Add option run-pre-commit = yes / no.

.github/workflows/tests.yml, CHANGES.rst, README.rst, doc/source/developing.rst, doc/source/versions.rst, pyproject.toml, setup.cfg, setup.py, tox.ini, zest/releaser/tests/pyproject-toml.txt, zest/releaser/tests/pyproject.toml, zest/releaser/vcs.py
- Added `pyproject.toml` and moved most metadata there. "Eat your own dog food." I am not sure if we can get rid of the remaining parts of `setup.py`.
- Add reader. I added `tomli` to the dependencies on Pythons earlier than 3.11. Chances are that you already have this via a different dependency. On 3.11 I use the built-in `tomllib`. 
- Add writer. This is not that different from how we write to `setup.py` or other files.
- Checked that `bin/prerelease` updates the version in our own `pyproject.toml`. I did not commit this.
This fixes issue #373.
=> Write version in pyproject toml if available

zest/releaser/pypi.py, zest/releaser/tests/baserelease.txt, zest/releaser/tests/functional-git.txt, zest/releaser/tests/pypi.txt, zest/releaser/tests/pypirc_new.txt, zest/releaser/tests/pypirc_old.txt, zest/releaser/vcs.py
Easy enough at first, but then the tests broke because my ~/.pypirc was found...  So some more fixes were needed.
=> Fix reading pypirc

CHANGES.rst, setup.py, tox.ini, zest/__init__.py
This is instead of deprecated pkg_resources based ones.
Note that this can be a problem in case `zest.releaser` is installed in combination with other packages in the `zest` namespace. But there are only a few such Plone related packages, so they won't usually be installed in the same virtual environment. And otherwise I can make new releases of those packages. Now seems a good time to do this.
Note that this needed a change in `tox.ini`, otherwise no tests were found.
=> Use native namespace packages for zest.releaser.

zest/releaser/release.py, zest/releaser/utils.py
Fixes the final part of issue #420.
=> Fixed detecting errors/warnings in output of the 'build' command.

CHANGES.rst, zest/releaser/utils.py
We only need to look at the exit code to see if it worked. See https://github.com/zestsoftware/zest.releaser/pull/415#issuecomment-1635596826
=> Ignore error output when calling `build`.

CHANGES.rst, README.rst, pyproject.toml, zest/releaser/longtest.py
=> Simplify longtest, which makes it support markdown

CHANGES.rst, zest/releaser/baserelease.py, zest/releaser/tests/baserelease.txt, zest/releaser/tests/release.txt, zest/releaser/tests/utils.txt, zest/releaser/utils.py
When a command fails, always ask the user to continue or not.  I hope with this we strike a good balance between showing error output, exit codes, and asking if the user wants to continue.
With the previous alpha release, the balance was not good for me.  The final `git push` used `stderr` to report that everything was fine, and then `postrelease` treated this as an error, and asked me if I wanted to continue.  Now we check the exit code.
@elisallenens @gforcada Since Reinout is unavailable for a while, can you review it, or simply try this branch out when releasing some packages?  I could also do another alpha release to more easily try it.
=> Check the exit code of a command, instead of relying on stderr

CHANGES.rst, zest/releaser/pypi.py
=> When reading pypirc config, read setup.cfg as well to override this.

zest/releaser/pypi.py, zest/releaser/release.py
I know this PR is not ready to merge, but would like to hear your feedback before polishing docs and writing tests.
I'm using zest.releaser with an `after_checkout` that builds the UI with Node.
I want to publish the built wheels/archives from a Github Action, using the official action that supports trusted publishing. See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
For that, I want zest.releaser to build everything but without uploading to Pypi. 
I would run it with:
```
[zest.releaser]
create-wheel = yes
upload-pypi = no
```
and `release --no-input`
What do you think?
> Note: I could also run the build commands directly in the Github Action instead of using `release`
=> Add `upload-pypi` option to disable upload to Pypi

CHANGES.rst, doc/source/developing.rst, doc/source/options.rst, zest/releaser/pypi.py, zest/releaser/release.py
=> (From Leplatrem): option upload pypi

tox.ini
The current specification of test dependencies via the `deps` keyword is effectively saying that in addition to both `test` and `recommended` extras there needs to be also `zest.releaser` installed.  This causes inconvenience for downstream packagers because it is creating some sort of circular dependency.
See also: https://peps.python.org/pep-0508/#extras
=> Use extras instead of deps in tox.ini

doc/source/versions.rst
The snippet above the fix uses `importlib.metadata` rather than `pkg_resources`.
=> chore(docs): no more pkg_resources

.github/workflows/tests.yml, CHANGES.rst, README.rst, pyproject.toml, tox.ini, zest/releaser/baserelease.py, zest/releaser/tests/functional-git.txt, zest/releaser/tests/functional-with-hooks.txt, zest/releaser/tests/pypirc.txt, zest/releaser/tests/pyproject-toml.txt, zest/releaser/utils.py, zest/releaser/vcs.py
This builds on PR #456, but restores Python 3.9 support by using `importlib_resources` (only on that version), and fix local errors where I do not understand that they are not going wrong on GitHub Actions.
See [my comment](https://github.com/zestsoftware/zest.releaser/pull/456#pullrequestreview-2654313660) on that PR.
=> pkgresources fix, but restore Python 3.9 support and fix local errors

CHANGES.rst, pyproject.toml, zest/releaser/pypi.py, zest/releaser/utils.py
We were already pulling this in via another dependency.
Remove even more remaining `pkg_resources` usage.
=> Add packaging to our dependencies.

CHANGES.rst, pyproject.toml
This added the `installer` argument to `DefaultIsolatedEnv`.
Fixes issue #465.
=> Require `build` 1.2.0 or higher.

CHANGES.rst, setup.cfg
I was just one minute too late with two tiny fixes to your PR. :-)
I rebased and force pushed the same branch.
No release needed for just these changes, but it avoids a `twine check` warning.
=> Set long_description_content_type to text/rst.
